#!/bin/bash

# wmname LG3D
numlockx
setxkbmap -option 'ctrl:nocaps'
# sudo nm-applet &>/dev/null &
while true
do
    updateRoot
    sleep 1m
done &
wall
xhost +
exec dwm
# exec ck-launch-session dbus-launch --sh-syntax --exit-with-session dwm
